[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build_release]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.prerelease]
dependencies = [
    "format",
    "build",
    "test"
]

[tasks.ci]
dependencies = [
    "test",
    "build_release",
    "package"
]

[tasks.lambda_package]
dependencies = [
    "build_release"
]
script = [
'''
mkdir -p dist/rotator
cp target/release/rotator dist/rotator/bootstrap
zip -j dist/rotator.zip dist/rotator/bootstrap
'''
]
